---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "parquettotiff"
description: Convert Cellpose Parquet files containing segmentation geometries into label-image TIFF files
keywords:
  - parquet
  - tiff
  - segmentation
  - cellpose
  - geometry
  - rasterization
  - label-image
  - microscopy
tools:
  - "parquettotiff":
      description: "Python script that converts a Cellpose Parquet file containing segmentation geometries into a label-image TIFF file by rasterizing WKB geometries"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: "MIT"
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - parquet:
        type: file
        description: Cellpose Parquet file containing segmentation geometries in WKB format
        pattern: "*.parquet"
    - tiff:
        type: file
        description: Original TIFF file that the segmentation was run on (used for dimension extraction)
        pattern: "*.{tiff,tif}"
        ontologies:
          - edam: "http://edamontology.org/format_3591"
    - compartment:
        type: string
        description: Compartment type identifier (e.g., nuclear, whole_cell) used in output filename

output:
  - tiff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.tiff":
          type: file
          description: Label-image TIFF file with rasterized segmentation masks
          pattern: "*.tiff"
          ontologies:
            - edam: "http://edamontology.org/format_3591"

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@mcmero"
maintainers:
  - "@mcmero"
