# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "sopa_cellpose"
description: Perform Cellpose segmentation on image patches using SOPA, then resolve and consolidate the segmentation boundaries from all patches into a unified output
keywords:
  - segmentation
  - cellpose
  - sopa
  - patches
  - boundaries
  - spatial
  - omics
  - microscopy
  - resolve
components:
  - sopa/segmentationcellpose
  - sopa/resolvecellpose
input:
  - ch_patches:
      type: channel
      description: |
        The input channel containing image patches with metadata for Cellpose segmentation
        Structure: [ val(meta), path(zarr), val(index), val(n_patches), val(nuclear_channel), val(membrane_channels) ]
      pattern: "*.zarr"
  - ch_spatial_data:
      type: channel
      description: |
        The input channel containing spatial data in zarr format
        Structure: [ val(meta), path(zarr) ]
      pattern: "*.zarr"
output:
  - boundaries:
      type: file
      description: |
        Channel containing resolved Cellpose segmentation boundaries in parquet format
        Structure: [ val(meta), path(parquet) ]
      pattern: "*.parquet"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@mcmero"
maintainers:
  - "@mcmero"
