## yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "sopa_segment_wbacksub"
description: Perform complete cell segmentation pipeline with background subtraction followed by SOPA segmentation for both nuclear and whole-cell compartments, then extract cell measurements as GeoJSON annotations
keywords:
  - segmentation
  - sopa
  - cellpose
  - background
  - subtraction
  - nuclear
  - whole-cell
  - cell
  - measurement
  - spatial
  - omics
  - microscopy
  - geojson
  - annotations
  - preprocessing
components:
  - backgroundsubtract
  - sopa_segment
input:
  - ch_sopa_wbacksub:
      type: channel
      description: |
        The input channel containing sample metadata and TIFF files with channel information for background subtraction and SOPA segmentation
        Structure: [ val(sample), path(tiff), val(nuclear_channel), val(membrane_channels) ]
      pattern: "*.{tiff,tif}"
output:
  - annotations:
      type: file
      description: |
        Channel containing GeoJSON files with cell measurements and annotations
        Structure: [ val(meta), path(geojson) ]
      pattern: "*.geojson"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@mcmero"
maintainers:
  - "@mcmero"
