# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "sopa_segment"
description: Perform complete cell segmentation using SOPA (Spatial Omics Python Analysis) for both nuclear and whole-cell compartments, then extract cell measurements and export as GeoJSON annotations
keywords:
  - segmentation
  - sopa
  - cellpose
  - nuclear
  - whole-cell
  - cell
  - measurement
  - spatial
  - omics
  - microscopy
  - geojson
  - annotations
components:
  - sopa_segment_compartment
  - cellmeasurement
input:
  - ch_sopa:
      type: channel
      description: |
        The input channel containing TIFF files with nuclear and membrane channel information
        Structure: [ val(meta), path(tiff), val(nuclear_channel), val(membrane_channels) ]
      pattern: "*.{tiff,tif}"
output:
  - annotations:
      type: file
      description: |
        Channel containing GeoJSON files with cell measurements and annotations
        Structure: [ val(meta), path(geojson) ]
      pattern: "*.geojson"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@mcmero"
maintainers:
  - "@mcmero"
