---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "extractmarkers"
description: Extract markers, exposure times, and background channels from COMET OME-TIFF files and output as CSV compatible with mcmicro's background_subtraction tool
keywords:
  - markers
  - ome-tiff
  - metadata
  - exposure
  - background
  - microscopy
  - mcmicro
tools:
  - "extractmarkers":
      description: "Python script that extracts markers from COMET OME-TIFF and writes comma-delimited output containing markers, exposure times and background channels compatible with input expected by mcmicro's background_subtraction tool"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: "MIT"
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - tiff:
        type: file
        description: COMET OME-TIFF file containing multi-channel microscopy data with embedded metadata
        pattern: "*.{tiff,tif}"
        ontologies:
          - edam: "http://edamontology.org/format_3591"

output:
  - markers:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "${prefix}_markers.csv":
          type: file
          description: CSV file containing marker names, background channels, exposure times, and removal flags
          pattern: "*_markers.csv"
          ontologies:
            - edam: "http://edamontology.org/format_3752"

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@mcmero"
maintainers:
  - "@mcmero"
