---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: COMBINECHANNELS
description: |
  Outputs a 2-channel OME-TIFF with nuclear and membrane channels. Combines multiple
  membrane channels into a single channel using specified method. The nuclear channel
  is retained as-is, and the membrane channels are combined using the specified method
  (product or maximum). If >1 membrane channel is provided, the channel name becomes
  "combined_membrane", otherwise it retains the original membrane channel name.
keywords:
  - cell segmentation
  - spatial biology
  - channel combination
  - image processing
tools:
  - combinechannels:
      description: Combines multiple membrane channels into a single channel using specified method
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: "MIT"
      identifier: ""

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - tiff:
      type: file
      description: Input TIFF image file for segmentation
      pattern: "*.{tiff,tif}"
      ontologies:
        - edam: "http://edamontology.org/format_3727"
  - nuclear_channel:
      type: integer
      description: Channel number for nuclear staining (0-indexed)
  - membrane_channels:
      type: string
      description: Colon-separated list of membrane channel numbers
  - combine_method:
      type: string
      description: Method for combining membrane channels
      pattern: "{prod,max}"

output:
  - combined_tiff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "${prefix}_combined_channels.tiff":
          type: file
          description: A 2-channel OME-TIFF with nuclear and combined membrane channels.
          pattern: "{prefix}_combined_channels.tiff"
          ontologies:
            - edam: "http://edamontology.org/format_3727"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@mcmero"
maintainers:
  - "@mcmero"
