# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "sopa_segment_compartment"
description: Perform compartment segmentation using SOPA with Cellpose, converting TIFF images to zarr format, creating patches, running segmentation, and converting results back to TIFF
keywords:
  - segmentation
  - sopa
  - cellpose
  - spatial
  - omics
  - microscopy
  - compartment
  - zarr
  - patches
components:
  - sopa_cellpose
  - sopa/convert
  - sopa/patchifyimage
  - parquettotiff
input:
  - ch_sopa:
      type: channel
      description: |
        The input channel containing TIFF files with nuclear and membrane channel information
        Structure: [ val(meta), path(tiff), val(nuclear_channel), val(membrane_channels) ]
      pattern: "*.{tiff,tif}"
  - compartment:
      type: string
      description: |
        Compartment type identifier for segmentation (e.g., nuclear, whole_cell)
output:
  - zarr:
      type: file
      description: |
        Channel containing zarr spatial data files
        Structure: [ val(meta), path(zarr) ]
      pattern: "*.zarr"
  - tiff:
      type: file
      description: |
        Channel containing segmented compartment TIFF files
        Structure: [ val(meta), path(tiff) ]
      pattern: "*.tiff"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@mcmero"
maintainers:
  - "@mcmero"
