---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "cellmeasurement"
description: Extract cell measurements from nuclear and whole-cell segmentation masks and export as GeoJSON annotations
keywords:
  - cell
  - measurement
  - segmentation
  - microscopy
  - image analysis
  - geojson
tools:
  - "cellmeasurement":
      description: "Groovy application that extracts Regions of Interest (ROIs) from whole cell and nuclear mask images, matches them based on their centroids, calculates measurements and exports the cell objects as GeoJSON annotations"
      homepage: "https://github.com/WEHI-SODA-Hub/cellmeasurement"
      documentation: "https://github.com/WEHI-SODA-Hub/cellmeasurement#readme"
      tool_dev_url: "https://github.com/WEHI-SODA-Hub/cellmeasurement"
      doi: ""
      licence: "MIT"
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - tiff:
        type: file
        description: TIFF file containing multi-channel image data
        pattern: "*.{tiff,tif}"
        ontologies:
          - edam: "http://edamontology.org/format_3591"
    - nuclear_mask:
        type: file
        description: Nuclear segmentation mask file in TIFF format
        pattern: "*.{tiff,tif}"
        ontologies:
          - edam: "http://edamontology.org/format_3591"
    - whole_cell_mask:
        type: file
        description: Whole-cell segmentation mask file in TIFF format
        pattern: "*.{tiff,tif}"
        ontologies:
          - edam: "http://edamontology.org/format_3591"

output:
  - annotations:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.geojson":
          type: file
          description: GeoJSON file containing cell measurements and annotations
          pattern: "*.geojson"
          ontologies:
            - edam: "http://edamontology.org/format_3464"

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@mcmero"
maintainers:
  - "@mcmero"
