# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "backgroundsubtract"
description: Perform background subtraction on OME-TIFF files by extracting marker metadata and applying background correction using mcmicro's backsub tool
keywords:
  - background
  - subtraction
  - markers
  - ome-tiff
  - mcmicro
  - backsub
  - microscopy
  - preprocessing
components:
  - extractmarkers
  - backsub
input:
  - ch_backsub:
      type: channel
      description: |
        The input channel containing OME-TIFF files for background subtraction
        Structure: [ val(meta), path(tiff) ]
      pattern: "*.{tiff,tif}"
output:
  - backsub_tif:
      type: file
      description: |
        Channel containing background-subtracted OME-TIFF files
        Structure: [ val(meta), path(backsub_tif) ]
      pattern: "*.ome.tif"
  - markers:
      type: file
      description: |
        Channel containing marker metadata CSV files
        Structure: [ val(meta), path(markers.csv) ]
      pattern: "markers.csv"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@mcmero"
maintainers:
  - "@mcmero"
