# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "mesmer_segment"
description: Perform cell segmentation using Mesmer for both nuclear and whole-cell compartments, then extract cell measurements and export as GeoJSON annotations
keywords:
  - segmentation
  - mesmer
  - nuclear
  - whole-cell
  - cell
  - measurement
  - microscopy
  - geojson
  - annotations
components:
  - mesmersegment
  - cellmeasurement
input:
  - ch_mesmer_segment:
      type: channel
      description: |
        The input channel containing sample metadata and TIFF files with channel information
        Structure: [ val(sample), val(run_backsub), val(run_mesmer), val(run_cellpose), path(tiff), val(nuclear_channel), val(membrane_channels) ]
      pattern: "*.{tiff,tif}"
output:
  - annotations:
      type: file
      description: |
        Channel containing GeoJSON files with cell measurements and annotations
        Structure: [ val(meta), path(geojson) ]
      pattern: "*.geojson"
  - whole_cell_tif:
      type: file
      description: |
        Channel containing whole-cell segmentation mask TIFF files
        Structure: [ val(meta), path(tiff) ]
      pattern: "*.tiff"
  - nuclear_tif:
      type: file
      description: |
        Channel containing nuclear segmentation mask TIFF files
        Structure: [ val(meta), path(tiff) ]
      pattern: "*.tiff"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@mcmero"
maintainers:
  - "@mcmero"
